app/routes.py
from flask import render_template, redirect, url_for, flash, request, abort, Blueprint, jsonify, session, current_app
from .models import db
from .forms import RegistrationForm, LoginForm, PostForm, CommentForm
from .models import User, Post, Comment
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_required, current_user, logout_user, login_user
from sqlalchemy.exc import IntegrityError
from werkzeug.utils import secure_filename
from sqlalchemy.orm import joinedload
import os


bp = Blueprint('app', __name__)

UPLOAD_FOLDER = 'static/profile_pics'
UPLOAD_POST_FOLDER = 'static/post_pics'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@bp.route('/')
def home():
    return render_template('home.html')


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        if form.password.data != form.confirm_password.data:
            flash('Passwords do not match. Please enter matching passwords.', 'danger')
            return render_template('register.html', form=form)

        hashed_password = generate_password_hash(form.password.data, method='pbkdf2:sha256')
        new_user = User(username=form.username.data, password=hashed_password)

        try:
            db.session.add(new_user)
            db.session.commit()
            flash('Account created successfully!', 'success')
            return redirect(url_for('app.login'))
        except IntegrityError:
            db.session.rollback()
            flash('Username already exists. Please choose a different username.', 'danger')

    return render_template('register.html', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            flash('Login successful!', 'success')
            login_user(user)
            session['profile_image'] = user.profile_image
            return redirect(url_for('app.home'))
        else:
            flash('Login unsuccessful. Please check your username and password.', 'danger')
    return render_template('login.html', form=form)


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('app.home'))


@bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def view_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment(content=form.content.data, post_id=post.id, user=current_user)
        db.session.add(new_comment)
        db.session.commit()
        flash('Comment added successfully!', 'success')
        return redirect(url_for('app.view_post', post_id=post_id))
    return render_template('view_post.html', post=post, form=form)


@bp.route('/create_post', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post(title=form.title.data, content=form.content.data, user=current_user)
        if form.image.data:
            image = form.image.data
            filename = secure_filename(image.filename)
            image.save(os.path.join(current_app.config['UPLOAD_POST_FOLDER'], filename))
            new_post.image = filename
        db.session.add(new_post)
        db.session.commit()
        flash('Post created successfully!', 'success')
        return redirect(url_for('app.home'))
    return render_template('create_post.html', form=form)


@bp.route('/edit_post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        abort(403)
    form = PostForm(obj=post)
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        if 'image' in request.files:
            image = request.files['image']
            if image.filename != '':
                filename = secure_filename(image.filename)
                image.save(os.path.join(current_app.config['UPLOAD_POST_FOLDER'], filename))
                post.image = filename
        else:
            post.image = form.current_image.data
        db.session.commit()
        flash('Post updated successfully!', 'success')
        return redirect(url_for('app.home'))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.current_image.data = post.image
    return render_template('edit_post.html', form=form, post=post)


@bp.route('/all_posts')
def all_posts():
    search_query = request.args.get('search', '')

    page = request.args.get('page', 1, type=int)
    per_page = 5

    if search_query:
        posts = Post.query.join(User).filter(User.id == Post.user_id).filter(Post.title.ilike(f'%{search_query}%')).options(joinedload(Post.user)).paginate(page=page, per_page=per_page, error_out=False)
    else:
        posts = Post.query.join(User).filter(User.profile_image != None).options(joinedload(Post.user)).paginate(page=page, per_page=per_page, error_out=False)
    
    form = CommentForm()
    return render_template('all_posts.html', all_posts_with_profile=posts, form=form)


@bp.route('/delete_post/<int:post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    with current_app.test_request_context():
        post = Post.query.get_or_404(post_id)
        if current_user != post.user:
            abort(403)
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted successfully!', 'success')
        return redirect(url_for('app.home'))


@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = current_user._get_current_object()

    posts = Post.query.filter_by(user_id=user.id).all()

    if request.method == 'POST':
        if 'profile_image' in request.files:
            file = request.files['profile_image']
            if file.filename != '':
                if file and allowed_file(file.filename):
                    filename = secure_filename(file.filename)
                    file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                    file.save(file_path)
                    user.profile_image = filename
                    db.session.commit()
                    flash('Profile picture uploaded successfully!', 'success')
                    return redirect(url_for('app.profile'))
                else:
                    flash('Invalid file format. Please upload an image file.', 'danger')

    for post in posts:
        post.comments

    db.session.add(user)

    return render_template('profile.html', user=user, posts=posts)


@bp.route('/update_profile_image', methods=['POST'])
@login_required
def update_profile_image():
    user = current_user
    if 'profile_image' in request.files:
        file = request.files['profile_image']
        if file.filename != '':
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(os.path.join(UPLOAD_FOLDER, filename))
                user.profile_image = filename
                db.session.commit()
                profile_image_url = url_for('static', filename=f'profile_pics/{filename}')
                session['profile_image'] = filename
                return jsonify({'profile_image_url': profile_image_url})
            else:
                return jsonify({'error': 'Invalid file format. Please upload an image file.'}), 400
    return jsonify({'error': 'No file uploaded.'}), 400


@bp.route('/edit_comment/<int:comment_id>', methods=['GET', 'POST'])
@login_required
def edit_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.user:
        abort(403)
    form = CommentForm(obj=comment)
    if form.validate_on_submit():
        comment.content = form.content.data
        db.session.commit()
        flash('Comment updated successfully!', 'success')
        return redirect(url_for('app.view_post', post_id=comment.post.id))
    return render_template('edit_comment.html', form=form, comment=comment)


@bp.route('/delete_comment/<int:comment_id>', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.user:
        abort(403)
    post_id = comment.post_id
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted successfully!', 'success')
    return redirect(url_for('app.view_post', post_id=post_id))

templates/all_posts.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Все посты</h1>
    <form action="{{ url_for('app.all_posts') }}" method="GET" class="form-inline mb-3">
        <input type="text" name="search" class="form-control mr-sm-2" placeholder="Поиск">
        <button type="submit" class="btn btn-primary">Найти</button>
    </form>
    {% for post_with_profile in all_posts_with_profile.items %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ post_with_profile.title }}</h5>
                <p class="card-text">{{ post_with_profile.content }}</p>
                {% if post_with_profile.image %}
                    <img src="{{ url_for('static', filename='post_pics/' + post_with_profile.image) }}" alt="Post Image" class="post-image" style="width: 300px; height: auto;">
                {% endif %}
                <p class="card-text">Автор: {{ post_with_profile.user.username }}</p>
                <div class="user-profile-picture-container">
                    {% if post_with_profile.user.profile_image %}
                        <img src="{{ url_for('static', filename='profile_pics/' + post_with_profile.user.profile_image) }}" alt="User Profile Picture" class="user-profile-picture">
                    {% else %}
                        <img src="{{ url_for('static', filename='default_profile_picture.jpg') }}" alt="Default Profile Picture" class="user-profile-picture">
                    {% endif %}
                </div>
                {% if current_user.is_authenticated and post_with_profile.user.id == current_user.id %}
                    <a href="{{ url_for('app.edit_post', post_id=post_with_profile.id) }}" class="btn btn-primary">Редактировать</a>
                    <form action="{{ url_for('app.delete_post', post_id=post_with_profile.id) }}" method="post" style="display: inline-block;">
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </form>
                {% endif %}
                <a href="{{ url_for('app.view_post', post_id=post_with_profile.id) }}" class="btn btn-primary">Комментарии</a>
            </div>
        </div>
    {% endfor %}
    <div class="pagination">
        {% if all_posts_with_profile.has_prev %}
            <a href="{{ url_for('app.all_posts', page=all_posts_with_profile.prev_num) }}">Previous</a>
        {% endif %}
        {% for page_num in all_posts_with_profile.iter_pages() %}
            {% if page_num %}
                {% if page_num != all_posts_with_profile.page %}
                    <a href="{{ url_for('app.all_posts', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <span>{{ page_num }}</span>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        {% if all_posts_with_profile.has_next %}
            <a href="{{ url_for('app.all_posts', page=all_posts_with_profile.next_num) }}">Next</a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{{ url_for('app.home') }}">Домой</a></li>
            {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('app.create_post') }}">Создать пост</a></li>
                <li><a href="{{ url_for('app.all_posts') }}">Посты</a></li>
                <li><a href="{{ url_for('app.profile', user_id=current_user.id) }}">Профиль</a></li>
                <li><a href="{{ url_for('app.logout') }}">Выход</a></li>
            {% else %}
                <li><a href="{{ url_for('app.create_post') }}">Создать пост</a></li>
                <li><a href="{{ url_for('app.all_posts') }}">Посты</a></li>
                <li><a href="{{ url_for('app.login') }}">Вход</a></li>
                <li><a href="{{ url_for('app.register') }}">Регистрация</a></li>
            {% endif %}
        </ul>
    </nav>
    {% block content %}{% endblock %}
</body>
</html>

templates/create_post.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <h1>Создать пост</h1>
    <form method="POST" action="{{ url_for('app.create_post') }}" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <label for="title">Заголовок:</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="content">Содержимое:</label>
            {{ form.content }}
        </div>
        <div class="form-group">
            <label for="image">Изображение:</label>
            {{ form.image }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

templates/edit_comment.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <h1>Edit Comment</h1>
    <form method="POST" action="{{ url_for('app.edit_comment', comment_id=comment.id) }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <label for="content">Content:</label>
            {{ form.content }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

templates/edit_post.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <h1>Редактировать пост</h1>
    <form id="editForm" method="POST" action="{{ url_for('app.edit_post', post_id=post.id) }}" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <label for="title">Заголовок:</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="content">Содержимое:</label>
            {{ form.content }}
        </div>
        {% if post.image %}
        <div class="form-group">
            <label for="current_image">Текущее изображение:</label><br>
            <img src="{{ url_for('static', filename='post_pics/' + post.image) }}" alt="Current Image" style="width: 300px; height: auto;">
        </div>
        {% endif %}
        <div class="form-group">
            <label for="image">Выберите файл:</label>
            {{ form.image }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    {% if current_user.is_authenticated %}
      <div class="jumbotron">
        <h1 class="display-4">Добро пожаловать, {{ current_user.username }}!</h1>
        <p class="lead">Это ваш блог. Начните новое обсуждение или присоединитесь к существующим.</p>
        <hr class="my-4">
        <p>Делитесь своим опытом и идеями.</p>
        <a class="btn btn-primary btn-lg" href="{{ url_for('app.create_post') }}" role="button">Создать пост</a>
        <a class="btn btn-primary btn-lg" href="{{ url_for('app.all_posts') }}" role="button">Просмотреть все посты</a>
      </div>
    {% else %}
      <div class="jumbotron">
        <h1 class="display-4">Добро пожаловать в блог!</h1>
        <p class="lead">Здесь вы можете делиться своими мыслями и идеями.</p>
        <hr class="my-4">
        <p>Присоединяйтесь к нашему сообществу и начинайте обсуждение.</p>
        <a class="btn btn-primary btn-lg" href="{{ url_for('app.login') }}" role="button">Войти</a>
        <a class="btn btn-primary btn-lg" href="{{ url_for('app.register') }}" role="button">Зарегистрироваться</a>
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <h1>Вход</h1>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class="flashes">
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    <form method="POST" action="{{ url_for('app.login') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <label for="username">Имя:</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="password">Пароль:</label>
            {{ form.password }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
    <p>У вас нет учетной записи? <a href="{{ url_for('app.register') }}">Регистрация</a></p>
</div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block title %}Профиль{% endblock %}

{% block content %}
    <div class="profile-container">
        <div class="profile-picture-container">
            <img id="profile-picture" src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}" alt="Profile Picture" class="profile-picture">
            <form id="upload-form" method="POST" enctype="multipart/form-data" style="display: none;">
                <label for="profile-image-upload" class="upload-label">
                    Изменить
                </label>
                <input type="file" name="profile_image" id="profile-image-upload" accept="image/*" style="display: none;" required>
                <button type="button" id="cancel-btn" class="btn-upload">Отмена</button>
                <button type="button" id="apply-image-btn" class="btn-upload">Применить</button>
                <input type="hidden" id="previous-profile-image" value="{{ session.get('profile_image', url_for('static', filename='default_profile_picture.jpg')) }}">
            </form>
        </div>
        <div class="user-info">
            <div class="profile-header">
                <h1>{{ user.username }}</h1>
            </div>
            <div class="profile-info">
                <p>Это ваш профиль. Здесь вы можете просмотреть свои последние действия.</p>
            </div>
            <div class="profile-posts">
                <h2>Последние посты:</h2>
                <ul class="post-list">
                    {% for post in posts %}
                        <li class="post-item">
                            <a href="{{ url_for('app.view_post', post_id=post.id) }}">{{ post.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>            
            <div class="profile-comments">
                <h2>Последние комментарии:</h2>
                <ul class="comment-list">
                    {% for comment in user.comments %}
                        <li class="comment-item">{{ comment.content }}</li>
                        <hr>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <script>
        function previewImage(event) {
            var input = event.target;
            var reader = new FileReader();
            reader.onload = function(){
                var img = document.getElementById('profile-picture');
                img.src = reader.result;
            };
            reader.readAsDataURL(input.files[0]);
            document.getElementById('apply-image-btn').style.display = 'block';
            document.getElementById('cancel-btn').style.display = 'block';
            document.getElementById('upload-form').style.display = 'flex';
        }
    
        document.getElementById('profile-image-upload').addEventListener('change', previewImage);
    
        document.getElementById('profile-picture').addEventListener('click', function() {
            document.getElementById('profile-image-upload').click();
        });
    
        document.getElementById('cancel-btn').addEventListener('click', function() {
            var previousImageUrl = document.getElementById('previous-profile-image').value;
            document.getElementById('profile-picture').src = previousImageUrl;
            document.getElementById('apply-image-btn').style.display = 'none';
            document.getElementById('cancel-btn').style.display = 'none';
            document.getElementById('upload-form').style.display = 'none';
        });
    
        document.getElementById('apply-image-btn').addEventListener('click', function() {
            var fileInput = document.getElementById('profile-image-upload');
            var file = fileInput.files[0];
    
            var formData = new FormData();
            formData.append('profile_image', file);
    
            fetch('/update_profile_image', {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                document.getElementById('profile-picture').src = data.profile_image_url;
                sessionStorage.setItem('profile_image_url', data.profile_image_url);
            })
            .catch(error => console.error('Ошибка загрузки изображения:', error));
        });
    
        document.addEventListener('DOMContentLoaded', function() {
            var profileImageURL = sessionStorage.getItem('profile_image_url');
            document.getElementById('profile-picture').src = profileImageURL || '{{ url_for("static", filename="default_profile_picture.jpg") }}';
        });
    </script>    
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <h1>Регистрация</h1>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class="flashes">
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    <form method="POST" action="{{ url_for('app.register') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <label for="username">Имя:</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="password">Пароль:</label>
            {{ form.password }}
        </div>
        <div class="form-group">
            <label for="confirm_password">Подтвердите пароль:</label>
            {{ form.confirm_password }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
    <p>У вас уже есть учетная запись? <a href="{{ url_for('app.login') }}">Авторизоваться</a></p>
</div>
{% endblock %}

templates/view_post.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
    {% if post.image %}
        <img src="{{ url_for('static', filename='post_pics/' + post.image) }}" alt="Post Image" style="width: 300px; height: auto;">
    {% endif %}
    <p>Автор: {{ post.user.username }}</p>
    <h2>Комментарии</h2>
    {% for comment in post.comments %}
        <div class="comment-container {% if comment.user == current_user %}current-user{% endif %}">
            <div class="comment">
                <p class="comment-text">{{ comment.content }}</p>
                <p class="comment-author">Автор: {{ comment.user.username }}</p>
                {% if current_user == comment.user %}
                    <a href="{{ url_for('app.edit_comment', comment_id=comment.id) }}" class="btn btn-primary">Редактировать</a>
                    <form action="{{ url_for('app.delete_comment', comment_id=comment.id) }}" method="post" style="display: inline-block;">
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </form>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    <form action="{{ url_for('app.view_post', post_id=post.id) }}" method="post" class="comment-form">
        {{ form.csrf_token }}
        <div class="form-group">
            <textarea name="content" placeholder="Введите комментарий"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Добавить комментарий</button>
    </form>     
</div>
{% endblock %}